title: Toukibi Monaka のページ
description: Toukibi Monaka のページの説明

theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io
aux_links:
  Twitter: https://twitter.com/

compress_html:
  blanklines: true
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'